### ISSUE TITLE
Create deliveryman entity routes

### ISSUE THREAD

**Issue by wfercosta** [wfercosta/rocketseat-gostack#1]
## Tasks
- [x] Create database migration for files entity (to save the avatar).
  - **Attributes:**
    - id (id da foto)
    - name (nome do arquivo);
    - path (caminho do arquivo);
    - created_at;
    - updated_at;
- [x] Create database migration for deliverymen entity.
  - **Attributes:**
    - id (id do entregador)
    - name (nome do entregador);
    - avatar_id (foto do entregador);
    - email (email do entregador)
    - created_at;
    - updated_at;
- [x] Create model for Deliveryman
- [x] Create model for File
- [x] Create a seeds for deliverymen, files, recipients entities

## Acceptance tests

**Index route: GET /deliverymen**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "OK" and a list of all deliveryman

**Show route: GET /deliverymen/:id**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "OK" and the deliveryman when it was successfully found
- [x] should return status "not found" and an error when the deliveryman was not found

**Store route: POST /deliverymen**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "bad request" and an error when the mandatory fields are not filled
- [x] should return status "bad request" and an error when the email is duplicated
- [x] should return status "created" and the deliveryman when it is successfully created

**Update route: PUT /deliverymen/:id**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "bad request" and an error when the mandatory fields are not filled
- [x] should return status "not found" and an error when the deliveryman was not found
- [x] should return status "OK" and the deliveryman when it is successfully updated

**Delete route: DELETE /deliverymen/:id**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "OK" and the deliveryman when it is successfully deleted
- [x] should return status "not found" and an error when the deliveryman was not found
