### ISSUE TITLE
Create delivery entity routes

### ISSUE THREAD

**Issue by wfercosta** [wfercosta/rocketseat-gostack#5]
## Tasks

- [x] Create database migration for delivery entity that relates a delivery with recipient and deliveryman
  - **Attributes:**
    - id (id da entrega)
    - recipient_id (referência ao destinatário);
    - deliveryman_id (referência ao entregador);
    - signature_id (referência à uma assinatura do destinatário, que será uma imagem);
    - product (nome do produto a ser entregue);
    - canceled_at (data de cancelamento, se cancelada);
    - start_date (data de retirada do produto);
    - end_date (data final da entrega);
    - created_at;
    - updated_at;
- [x] Create model for Delivery that associate Recipient and Deliveryman
- [x] Create a seeds for delivery entity

## Acceptance tests

**Index route: GET /deliveries**

- [x] should return status "not authorized" when requested without a token
- [x] should return status "OK" and a list of all deliveries

**Show route: GET /deliveries/:id**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "OK" and the delivery when it was successfully found
- [x] should return status "not found" and an error when the delivery was not found

**Store route: POST /deliveries**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "bad request" and an error when the mandatory fields are not filled
- [x] should return status "created" and the delivery when it is successfully created

**Update route: PUT /deliveries/:id**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "not found" and an error when the delivery was not found
- [x] should return status "OK" and the delivery when it is successfully updated

**Delete route: DELETE /deliveries/:id**
- [x] should return status "not authorized" when requested without a token
- [x] should return status "OK" and the delivery when it is successfully deleted
- [x] should return status "not found" and an error when the delivery was not found
