### ISSUE TITLE
Create deliveries problem routes

### ISSUE THREAD

**Issue by wfercosta** [wfercosta/rocketseat-gostack#7]
## Tasks
- [x] Create database migration for problems entity that relates a problem with delivery
  - **Attributes:**
    - id (id do entregador)
    - description (descrição do problema que o entregador teve);
    - created_at;
    - updated_at;
- [x] Create model for Problems
- [x] Create a seeds for Problems

## Acceptance tests

**Index route: GET /deliveries/:delivery/problems**

- [x] should return status "not authorized" when requested without a token
- [x] should return status "not found" and an error when the delivery was not found
- [x] should return status "OK" and a list of all delivery problems 

**Show route: POST /deliveries/:delivery/problems**

- [x] should return status "not found" and an error when the delivery was not found
- [x] should return status "bad request" an error when the mandatory fields are not filled
- [x] should return status "OK" and the problem when it was successfully created
