### ISSUE TITLE
Create cancel delivery route

### ISSUE THREAD

**Issue by wfercosta** [wfercosta/rocketseat-gostack#8]
## Tasks
- [x] Create database migration for deliveries to add cancellation properties
  - **Attributes:**
    - cancelled_at
    - reason_id (a delivery problem)

## Acceptance tests

**Patch route: PATCH /deliveries/:delivery/cancellation**

- [x] should return status "not authorized" when requested without a token
- [x] should return status "not found" and an error when the delivery and problem was not found
- [x] should return status "bad request" and an error when the mandatory fields are not filled
- [x] should return status "OK" and cancellation when successfuly patched
